{
  lib,
  clan-core,
  config,
  ...
}:

let
  suffix = config.clan.core.vars.generators.disk-id.files.diskId.value;
in
{
  imports = [
    clan-core.clanModules.disk-id
  ];

  # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
  # Otherwise your system might not boot because of missing partitions / filesystems

  # Use GRUB in BIOS (legacy) mode, not EFI
  boot.loader.grub.enable = true;
  boot.loader.grub.efiSupport = lib.mkDefault false;
  boot.loader.grub.device = config.disko.devices.disk.main.device;
  boot.loader.grub.forceInstall = lib.mkDefault true; # Ensure GRUB installs even if another bootloader is present
  # boot.loader.grub.extraConfig = ''
  #   set root=(hd0,gpt1)
  #   set prefix=(hd0,gpt1)/boot/grub
  # '';

  disko.devices.disk = {
    "main" = {
      # suffix is to prevent disk name collisions
      name = "main-" + suffix;
      type = "disk";
      # Set the following in flake.nix for each machine:
      # device = <uuid>;
      content = {
        type = "gpt";
        partitions = {
          "root" = {
            size = "100%";
            type = "8300";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          };
        };
      };
    };
    "swap" = {
      name = "swap-" + suffix;
      type = "disk";
      # Set the device in flake.nix or configuration.nix for this disk as well
      # device = <uuid>;
      content = {
        type = "gpt";
        partitions = {
          "swap" = {
            size = "100%";
            content = {
              type = "swap";
            };
          };
        };
      };
    };
  };
}
