worker_processes auto;

events {
    worker_connections 1024;
}

http {

    server_names_hash_bucket_size 128;
    include mime.types;
    # fallback in case we can't determine a type
    default_type application/octet-stream;
    # access_log /var/log/nginx/access.log combined;

    sendfile on;

    # upstream ticket_backend {
    #     server ticket_backend:8000 fail_timeout=0;
    # }

    server {
        listen 80;
        listen [::]:80;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            # return 404;
            return 301 https://$host$request_uri;
        }
    }

    include ssl.conf;
}
