server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 80;
    listen [::]:80;
    include error.conf;

    http2 on;

    server_name documentation.greensiren.co.uk;

    location / {
        return 410;
    }
}
