name: green_siren_services

services:
  prod-postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "Pornhub.com"
    volumes:
      - postgress_db:/var/lib/postgresql/data

  # portainer:
  #   image: portainer/portainer-ee:latest
  #   container_name: portainer
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ../docker-data/portainer-data:/data
  #   ports:
  #     - 9000:9000

  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hahahahahfakjhsdakj;fmvqop[i23409lckxnmvarioavokmqpoauiegvna[wos;kildz/5tklvahuipta;sjlvbihpua;kjtr]]
      - MYSQL_PASSWORD=hahahahahfakjhsdakj;fmvqop[i23409lckxnmvarioavokmqpoauiegvna[wos;kildz/5tklvahuipta;sjlvbihpua;kjtr]]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud_html:/var/www/html
    environment:
      - MYSQL_PASSWORD=hahahahahfakjhsdakj;fmvqop[i23409lckxnmvarioavokmqpoauiegvna[wos;kildz/5tklvahuipta;sjlvbihpua;kjtr]]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  nextcloud-cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud_html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
      - nginx

  nginx:
    build: ./containers/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - certbot-webroot:/var/www/certbot/:ro
      - certbot-cert:/etc/letsencrypt/:ro
      # - ../docker-data/radio/:/radio/:ro
      # - ./nginx/static_websites/:/static_websites/:ro
    links:
      - nextcloud
    volumes_from:
      - nextcloud
    # environment:
    #   - CI_JOB_TOKEN=${CI_JOB_TOKEN}

  # certbot:
  #   build: ./containers/certbotdocker
  #   volumes:
  #     - certbot-webroot:/var/www/certbot/:rw
  #     - certbot-cert:/etc/letsencrypt/:rw
  #   depends_on:
  #     - nginx

volumes:
  postgress_db:
  nextcloud_db:
  nextcloud_html:
  certbot-webroot:
  certbot-cert:
