server {
    listen 443 ssl;
    listen [::]:443 ssl;
    include error.conf;

    http2 on;

    server_name documentation.greensiren.co.uk;

    location / {
        return 410;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    include error.conf;

    http2 on;

    server_name valentines.greensiren.co.uk;

    location / {
        return 410;
    }
}
